#!/usr/bin/env python3
"""Export everything the browser engine needs into webapp/data.js (boards + net weights, base64),
plus webapp/testcase.json so the JS engine can be cross-checked against PyTorch with node.

The standalone web app re-implements rules + encoding + the GNN forward + MCTS in pure JS; this
script just ships it the precomputed per-board graph/static features and the trained weights, so
the browser needs no Python, scipy, or torch.
"""

from __future__ import annotations

import base64
import json
import sys
from pathlib import Path

import numpy as np
import torch

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from tilinggo.nn.encoding import encode_states, static_board  # noqa: E402
from tilinggo.rules.gostate import BLACK, GoState  # noqa: E402
from tilinggo.sit.checkpoint import load_checkpoint  # noqa: E402
from tilinggo.ui import server  # noqa: E402 (imports board builders / catalogue; starts no server)

CKPT = "results/universal/champion.pt"
# catalogue boards to embed (skip 19x19 — too slow for a pure-JS MCTS)
KEYS = [k for k, _, _ in server.TILINGS if k != "rect19"]


def b64f(arr) -> str:
    return base64.b64encode(np.asarray(arr, dtype="<f4").tobytes()).decode("ascii")


def b64i(arr) -> str:
    return base64.b64encode(np.asarray(arr, dtype="<i4").tobytes()).decode("ascii")


def weight_blob(net) -> str:
    """Flat float32 of every parameter the JS net needs, in a fixed order the loader mirrors."""
    sd = net.state_dict()
    order = ["input.0.weight", "input.0.bias", "input.2.weight", "input.2.bias"]
    for b in range(net.cfg.blocks):
        order += [f"blocks.{b}.norm.weight", f"blocks.{b}.norm.bias",
                  f"blocks.{b}.mlp.0.weight", f"blocks.{b}.mlp.0.bias",
                  f"blocks.{b}.mlp.2.weight", f"blocks.{b}.mlp.2.bias"]
    order += ["final_norm.weight", "final_norm.bias",
              "policy_node.weight", "policy_node.bias",
              "pass_head.weight", "pass_head.bias",
              "value_head.0.weight", "value_head.0.bias", "value_head.2.weight", "value_head.2.bias",
              "ownership_head.weight", "ownership_head.bias",
              "score_head.0.weight", "score_head.0.bias", "score_head.2.weight", "score_head.2.bias"]
    flat = np.concatenate([sd[k].detach().cpu().numpy().astype("<f4").ravel() for k in order])
    return base64.b64encode(flat.tobytes()).decode("ascii")


def board_record(key):
    board = server._make_board(key, komi=5.5)
    g = board.graph
    sb = static_board(g)
    static = np.concatenate([sb.degree_onehot, sb.dist, sb.pe], axis=1).astype("<f4")  # [N,24]
    return {
        "label": server._LABELS[key],
        "n": int(g.num_nodes),
        "komi": float(board.komi),
        "coords": b64f(np.asarray(g.coords, dtype="<f4").ravel()),     # [N*2]
        "edges": b64i(np.asarray(g.edges, dtype="<i4").ravel()),       # [E*2]
        "static": b64f(static.ravel()),                                # [N*24]
    }


def main() -> int:
    out = Path(__file__).resolve().parent.parent / "webapp"
    out.mkdir(exist_ok=True)
    net, _ = load_checkpoint(CKPT)
    net.eval()

    boards = {}
    for key in KEYS:
        boards[key] = board_record(key)
        print(f"  board {key:14s} N={boards[key]['n']}")

    data_js = (
        "// auto-generated by scripts/export_webapp.py — boards + trained net weights (base64)\n"
        f"const CFG = {{in_dim: {net.cfg.in_dim}, hidden: {net.cfg.hidden}, blocks: {net.cfg.blocks}}};\n"
        f"const WEIGHTS_B64 = \"{weight_blob(net)}\";\n"
        f"const BOARDS = {json.dumps(boards)};\n"
        "if (typeof module !== 'undefined') module.exports = {CFG, WEIGHTS_B64, BOARDS};\n"
    )
    (out / "data.js").write_text(data_js)
    print(f"wrote {out/'data.js'}  ({len(data_js)/1e6:.2f} MB, {len(boards)} boards)")

    # ---- node cross-check test case: a real position labelled by PyTorch ----
    board = server._make_board("rect9", komi=5.5)
    rng = np.random.default_rng(0)
    s = board.new_game()
    for _ in range(8):
        legal = np.where(s.legal_moves()[: board.n])[0]
        s = s.play(int(rng.choice(legal)))
    st = GoState(board, s.colors.copy(), to_move=s.to_move, move_num=s.move_num)
    with torch.no_grad():
        o = net.forward(encode_states([st]))
    own = torch.softmax(o["ownership"][0], dim=-1).numpy()
    tc = {
        "key": "rect9", "n": board.n, "to_move": int(st.to_move), "move_num": int(st.move_num),
        "colors": st.colors.astype(int).tolist(),
        "policy": o["policy_logits"][0].numpy().astype(float).tolist(),   # length n+1 (pre-softmax, masked)
        "value": float(o["value"][0]),
        "own_signed": (own[:, 0] - own[:, 1]).astype(float).tolist(),
        "score": float(o["score"][0]),
    }
    (out / "testcase.json").write_text(json.dumps(tc))
    print(f"wrote {out/'testcase.json'}  (rect9, move {st.move_num})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
