#!/usr/bin/env python3
"""Export the diamond-cubic 3D boards + weights → webapp/data3d.js (for the three.js page).

Same baked format as data.js (the engine is geometry-blind), plus `coords3` — the true 3D
lattice positions the renderer orbits around. Run scripts/build_3d.py after this.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "scripts"))

from export_webapp import b64f, b64i, weight_blob  # noqa: E402  (shared bake helpers)
from tilinggo.nn.encoding import static_board  # noqa: E402
from tilinggo.rules import Board  # noqa: E402
from tilinggo.sit.checkpoint import load_checkpoint  # noqa: E402
from tilinggo.tilings import diamond  # noqa: E402

CKPT = "results/universal/champion.pt"
SIZES = {"diamond_c2": 2, "diamond_c3": 3}
LABELS = {"diamond_c2": "Diamond cubic · small", "diamond_c3": "Diamond cubic · large"}


def main() -> int:
    net, _ = load_checkpoint(CKPT)
    net.eval()
    boards = {}
    for key, cells in SIZES.items():
        bg = diamond.generate(cells=cells)
        board = Board(bg, komi=5.5)
        sb = static_board(bg)
        static = np.concatenate([sb.degree_onehot, sb.dist, sb.pe], axis=1).astype("<f4")
        boards[key] = {
            "label": LABELS[key],
            "n": int(bg.num_nodes),
            "komi": float(board.komi),
            "coords": b64f(np.asarray(bg.coords, dtype="<f4").ravel()),       # 2D projection
            "coords3": b64f(np.asarray(bg.meta["coords3"], dtype="<f4").ravel()),  # [N*3]
            "edges": b64i(np.asarray(bg.edges, dtype="<i4").ravel()),
            "static": b64f(static.ravel()),
        }
        print(f"  {key}: N={bg.num_nodes} E={len(bg.edges)}")

    out = REPO / "webapp" / "data3d.js"
    out.write_text(
        "// auto-generated by scripts/export_3d.py — diamond-cubic boards + weights\n"
        f"const CFG = {{in_dim: {net.cfg.in_dim}, hidden: {net.cfg.hidden}, blocks: {net.cfg.blocks}}};\n"
        f"const WEIGHTS_B64 = \"{weight_blob(net)}\";\n"
        f"const BOARDS = {json.dumps(boards)};\n"
        "if (typeof module !== 'undefined') module.exports = {CFG, WEIGHTS_B64, BOARDS};\n")
    print(f"wrote {out} ({out.stat().st_size/1e6:.2f} MB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
